#run analysis
../../Chicago/Chicago_reg../../gen/Dallas/Dallas_reg: ../../Data/Dallas/Dallas_cleaned.csv ../../Data/Chicago/Chicago_cleaned.csv analyze.R
	R --vanilla --args "" < "analyze.R"
	

../../gen/Mexico/Data_reg: ../../Data/Mexico/Mexico_cleaned.csv analyze.R
	R --vanilla --args "" < "analyze.R"
	
